#!/bin/sh
setxkbmap -option caps:none

gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh
xset r rate 300 30
xsetroot -solid black

xcompmgr &
gnome-screensaver &
nm-applet &
/home/jahuang/.scripts/monitor_setup

exec /home/jahuang/.cabal/bin/xmonad
