#!/bin/sh
setxkbmap -option caps:none

gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh
xset r rate 300 30
xsetroot -solid black

xscreensaver -no-splash &
/usr/libexec/notification-daemon &

/home/jahuang/.scripts/monitor_setup

exec xmonad-start
