#!/usr/bin/env bash

exec mplayer -shuffle -nosound -really-quiet \
  -nolirc -nostop-xscreensaver -ss $(($RANDOM%10800)) -wid \
  $XSCREENSAVER_WINDOW -fs -loop 0 -vo gl_nosw\
  $HOME/screensavers/*
